#!/bin/zsh

# disable flow control
stty stop undef
stty start undef

# edit the current command in vim with ctrl-e
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^e' edit-command-line

# use lf to switch directories
lfcd () {
	tmp=$(mktemp)
	lf -last-dir-path="$tmp" "$@"
	if [ -f "$tmp" ]
	then
		dir=$(cat "$tmp")
		rm -f "$tmp" >/dev/null
		[ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
	fi
	clear
}
bindkey -s '^o' 'lfcd\n'
