#!/bin/sh

# start the scripts in xinitrc.d
if [ -d '/etc/X11/xinit/xinitrc.d' ]
then
	for f in '/etc/X11/xinit/xinitrc.d/?*.sh'
	do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# start the session
lxsession -a &

# Keyboard Layout
setxkbmap de &

# start the compositor
picom -f &

# Wallpaper
#xwallpaper --zoom "/data/pictures/wallpapers/sun.png" &
hsetroot -solid '#232323' &

# jack2 setup
start_jack2.sh

# start redshift
redshift -O 3500

# start dwmblocks
dwmblocks &

# bluetooth applet
blueman-applet &

# enable automatic locking
xautolock -time 5 -locker slock -corners 00-- &

# remove the mouse when idle
unclutter &

# set character repeatition rate
xset r rate 300 50 &

# start dwm
while true
do
	dwm >/dev/null 2>&1
done
exec dwm
