#!/bin/sh

# start the scripts in xinitrc.d
if [ -d '/etc/X11/xinit/xinitrc.d' ]
then
	for f in '/etc/X11/xinit/xinitrc.d/?*.sh'
	do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# load Xresources
[ -f ${XDG_CONFIG_HOME:-$HOME/.config}/X11/Xresources ] && xrdb -merge -I$HOME ${XDG_CONFIG_HOME:-$HOME/.config}/X11/Xresources

# keyrings
#[ -d ${XDG_DATA_HOME:-$HOME/.local/share}/keyrings ] || mkdir -p ${XDG_DATA_HOME:-$HOME/.local/share}/keyrings
#source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# start the session
lxsession -a &

# Keyboard Layout
setxkbmap de &

# start the compositor
picom -f &

# Wallpaper
xwallpaper --zoom "${XDG_CONFIG_HOME:-$HOME/.config}/current_wallpaper" &
#hsetroot -solid '#232323' &

# start redshift
redshift -O 3500

# start dunst
dunst &

# start dwmblocks
dwmblocks &

# bluetooth applet
blueman-applet &

# enable automatic locking
xautolock -time 5 -locker slock -corners 00-- &

# remove the mouse when idle
unclutter &

# set character repeatition rate
xset r rate 300 50 &

# start dwm
while true
do
	dwm >/dev/null 2>&1
done
exec dwm
