#!/bin/sh

# neovim
alias vim='nvim'

# update
alias mirror='sudo reflector --protocol https --latest 49 --number 25 -c Germany --sort rate --verbose --save /etc/pacman.d/mirrorlist'
alias cupdnc='paru -Syyu --devel --noconfirm; paru -c --noconfirm; paru -Sc --noconfirm'
alias cupd='paru -Syyu --devel; paru -c; paru -Sc'

# nvidia
alias gpust='nvidia-smi'

# list
alias exa='exa --group-directories-first'
alias ls='exa'
alias l='exa'
alias la='exa --all'
alias ll='exa -all --long'
alias lt='exa --tree'
alias ldir='exa --only-dirs'

# change directory
alias cd..='cd ..'
alias cd...='cd ../..'
alias cd....='cd ../../..'

# typos
alias dc='cd'
alias pdw='pwd'
alias sl='ls'

# colorize grep
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# documents view
alias img='sxiv'
alias pdf='zathura'

# TeX Live
alias tllm='tllocalmgr'

# ping test
alias tping='ping archlinux.org'

# suckless
alias sucklrcp='sudo cp config.def.h config.h && sudo make clean install; sudo make clean'

# git
alias dotfiles="git --git-dir=${XDG_DATA_HOME:-$HOME/.local/share}/dotfiles/ --work-tree=$HOME"
alias sucklgit="git --git-dir=$HOME/.local/source/suckless/.git --work-tree=$HOME/.local/source/suckless"

# calculator
alias calc='echo CALCULATOR && bc -q'

# calendar
alias cal='cal -m'
