#!/bin/sh

# update
alias mirror='sudo reflector --country Germany --protocol https --latest 50 --fastest 15 --age 18 --sort rate --verbose --save /etc/pacman.d/mirrorlist'
alias cupdnc='paru -Syyu --devel --noconfirm; paru -c --noconfirm; paru -Sc --noconfirm'
alias cupd='paru -Syyu --devel; paru -c; paru -Sc'

# list
alias lsd='lsd --classify --group-dirs first'
alias ls='lsd'
alias l='lsd'
alias la='lsd --all'
alias ll='lsd -all --long'
alias lt='lsd --tree'

# change directory
alias cd..='cd ..'
alias cd...='cd ../..'
alias cd....='cd ../../..'
alias cd.....='cd ../../../..'

# typos
alias dc='cd'
alias pdw='pwd'
alias sl='ls'

# colorize grep
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# documents view
alias img='sxiv'
alias pdf='zathura'

# ping test
alias tping='ping archlinux.org'

# suckless
alias sucklrcp='sudo cp config.def.h config.h && sudo make clean install; sudo make clean'

# git
alias dotfiles="git --git-dir=${XDG_DATA_HOME:-$HOME/.local/share}/dotfiles/ --work-tree=$HOME"

# calculator
alias calc='echo CALCULATOR && bc -q'

# calendar
alias cal='cal -m'
